[package]
name = "protocol"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "protocol"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "0.26.0"
solana-sdk = "1.14.11"
checked_decimal_macro = "0.1.4"
wasm-bindgen = "0.2.83"
bytemuck = "1.12.3"
wasm-bindgen-futures = "0.4.33"
js-sys = "0.3.60"
serde = "1.0.152"

[dependencies.web-sys]
version = "0.3.4"
features = [ 
    "console"
]
