[features]
seeds = false
skip-lint = false

[workspace]
members = [
    "programs/protocol",
    "programs/oracle"
]

[programs.localnet]
protocol = "Av5ZsxvBS28uB7yrusf1t2hXupvbeXA5V1nFD73iHRoL"
oracle = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
[programs.devnet]
protocol = "Av5ZsxvBS28uB7yrusf1t2hXupvbeXA5V1nFD73iHRoL"
oracle = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[test]
startup_wait = 10000

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000"
