#[derive(Debug, PartialEq)]
pub enum LibErrors {
    ToBeDefined,
    NotEnoughQuoteQuantity,
    NotEnoughBaseQuantity,
    UserAllowedBorrowExceeded,
    LendServiceNone,
    SwapServiceNone,
    OracleNone,
    QuoteOracleNone,
    OracleAlreadyEnabled,
    ConfidenceHigherThanPrice,
    StrategyNoLend,
    StrategyNoSwap,
    StrategyNoTrade,
    StrategyMissing,
    CannotBorrow,
    RepayLowerThanFee,
    CannotAddStrategy,
    CannotAddPosition,
}
