[package]
name = "core-lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
checked_decimal_macro = "0.1.4"
vec_macro = { path = "../vec_macro"}
borsh = "0.10.2"
anchor-lang = "0.26.0"